Models/Domain/BlogPost.cs
namespace _1_Application.Models.Domain;

public class BlogPost
{
    public long Id {set;get;}

    public string Heading{set;get;}

    public string PageTitle{set;get;}

    public string Content{set;get;}

    public string ShortDescription{set;get;}

    public string FeaturedImageUrl{set;get;}

    public string UrlHandler{set;get;}

    public DateTime PublishedDate{set;get;}

    public string Author{set;get;}

    public bool Visible{set;get;}

    public ICollection<Tag> Tags{set;get;}



}

Models/Domain/Tag.cs
namespace _1_Application.Models.Domain;

public class Tag
{
    public long Id{set;get;}

    public string Name{set;get;}

    public string DisplayName{set;get;}

        public ICollection<BlogPost> Tags{set;get;}

}

Models/ErrorViewModel.cs
namespace _1_Application.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/ViewModels/AddTagRequest.cs
namespace _1_Application.Models.ViewModels;

public class AddTagRequest
{
    
    public string Name{get;set;}

    public string DisplayName{set;get;}

}

Models/ViewModels/EditTagRequest.cs
namespace _1_Application.Models.ViewModels{

public class EditTagRequest
{
    public long Id{get;set;}
    public string Name{get;set;}

    public string DisplayName{set;get;}

}
}

Controllers/AdminTagsController.cs
using Microsoft.AspNetCore.Mvc;
using _1_Application.Models.ViewModels;
using _1_Application.Data;
using _1_Application.Models.Domain;
using _1_Application.Repo;
using Microsoft.EntityFrameworkCore;

namespace _1_Application.Controllers;
public class AdminTagsController : Controller
{
     private readonly ITagRepository _tagRepository;

    public AdminTagsController(ITagRepository tagRepository)
    {
        _tagRepository = tagRepository;
    }


    [HttpGet]
    public IActionResult Add()
    {
        return View("Add");
    }

    [HttpPost]
    [ActionName("Add")]
    public async Task<IActionResult> AddTag(AddTagRequest addTagRequest)
    {
        var name = addTagRequest.Name;
        var displayName = addTagRequest.DisplayName;

        var tag = new Tag
        {
            Name = addTagRequest.Name,
            DisplayName=addTagRequest.DisplayName
        };

        var tags = await _tagRepository.AddTagAsync(tag);
        
        return RedirectToAction("List");

    }
    [HttpGet]
    [ActionName("List")]
    public async Task<IActionResult> List()
    {
        var tags = await _tagRepository.GetAllAsync();
        return View(tags);
    }

    [HttpGet]
    [ActionName("Edit")]
    public async Task<IActionResult> Edit(long id)
    {
        var tag = await _tagRepository.FindByIdAsync(id);
        if(tag == null)
        {
            return View(null);
        } 
        var editTagRequest = new EditTagRequest
        {
            Id = tag.Id,
            Name = tag.Name,
            DisplayName = tag.DisplayName
        };

        return View(editTagRequest);

    }

    [HttpPost]
    public async Task<IActionResult> Edit(EditTagRequest editTagRequest)
    {
        var tag = await _tagRepository.EditTagAysnc(editTagRequest);

        return RedirectToAction("List");
        

    }


    [HttpPost]
    public async Task<IActionResult> Delete(EditTagRequest editTagRequest)
    {
        var tag = await _tagRepository.DeleteTagAsync(editTagRequest);
         return RedirectToAction("List");

    }

}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using _1_Application.Models;


namespace _1_Application.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/AdminTags/Add.cshtml
@model _1_Application.Models.ViewModels.AddTagRequest;

@{
    ViewData["Title"] = "Add New Tag";
}
<h1>Add New Tag - Admin Functionality</h1>


<div class="bg-secondary bg-opacity-10 py-2">

    <div class="container">
        <form  method="post">

            <div class="mb-3">
                <label class="form-label">Name</label>
                <input class="form-control" type="text" id="name" asp-for="Name">
            </div>

            <div class="mb-3">
                <label class="form-label">Display Name</label>
                <input class="form-control" type="text" id="displayName" asp-for="DisplayName">
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        
        </form>
    </div>

</div>

Views/AdminTags/Edit.cshtml
@model _1_Application.Models.ViewModels.EditTagRequest;

@{
    ViewData["Title"] = "Add New Tag";
}
<h1>Edit Tag - Admin Functionality</h1>


<div class="bg-secondary bg-opacity-10 py-2">

    <div class="container">
        <form  method="post">


        <div class="mb-3">
                <label class="form-label">Id</label>
                <input class="form-control" type="number" id="name" asp-for="Id"  readonly>
            </div>

            <div class="mb-3">
                <label class="form-label">Name</label>
                <input class="form-control" type="text" id="name" asp-for="Name" required>
            </div>

            <div class="mb-3">
                <label class="form-label">Display Name</label>
                <input class="form-control" type="text" id="displayName" asp-for="DisplayName" required>
            </div>

            <div class="mb-3">
                <button type="submit" class="btn btn-primary">Update</button>
                <button type="submit" class="btn btn-danger"
                asp-area="" asp-controller="AdminTags" asp-action="Delete"
                >Delete</button>


            </div>
        
        </form>
    </div>

</div>

Views/AdminTags/List.cshtml
@model List<_1_Application.Models.Domain.Tag>
@{
    ViewData["Title"] = "View All Tag";
}

<h1>View All  Tag - Admin Functionality</h1>

    @if(Model!=null){
         <table class="table">

        <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Name</th>
            <th scope="col">Display Name</th>
            <th scope="col"></th>
        </tr>

        <tbody>
        @foreach(var tag in Model){
            <tr>
                <td>@tag.Id</td>
                <td>@tag.Name</td>
                <td>@tag.DisplayName</td>
                <td>
                <a asp-area=""
                   asp-controller="AdminTags"
                   asp-action="Edit"
                   asp-route-id="@tag.Id"
                >
                Edit
                </a>
                </td>
            </tr>

        }     
        </tbody>

  </thead>

</table>
    }
    else{
        <p>No Tag Found</p>
    }

   

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - _1_Application</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/_1_Application.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Blogiee</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                          Admin
                          </a>
                         <ul class="dropdown-menu">
                              <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="Add">Add Tag</a></li>
                              <li><a class="dropdown-item" asp-area="" asp-controller="AdminTags" asp-action="List">Show All Tags</a></li>

                        </ul>
        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - _1_Application - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>